config/routes.rb
Rails.application.routes.draw do


  get  'mypage', to: 'users#me'
  get  'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'mygroup', to: 'groups#mygroup'
  get 'addgroup', to: 'group_users#new'
  post  'addgroup', to: 'group_users#create'

  root 'top#index'

  resources :users


  resources :groups do
    resources :posts, only: %i[new create edit update]
  end

  

  end


  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
   
    #アソシエーション 
    has_many :group_user
    has_many :users, through: :group_user
    accepts_nested_attributes_for :group_user

    has_many :posts

    validates :name,
       presence: true,
       uniqueness: true


end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  #アソシエーション 
  belongs_to :user
  belongs_to :group

  #validation
  validates :user_id, presence: true
  validates :group_id, presence: true

  #一意の組み合わせを検証
  validates_uniqueness_of :group_id , scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord

    #アソシエーション 
    belongs_to :group
    belongs_to :user

    validates :content,
        presence: true

    # validates :user_id, presence: true on: :update
    
   
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    #アソシエーション 
    has_many :group_user
    has_many :groups, through: :group_user
    has_many :posts
   
    #emailのvalidationオプション
    before_save {self.email= email.downcase}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name,
       presence: true,
       uniqueness: true,
       length: {maximum: 16}
    
    validates :email,
       presence: true,
       length: {maximum: 120},
       format: {with:VALID_EMAIL_REGEX},
       uniqueness: true   

    validates  :password,
       presence: true,
       length: { minimum: 6}


       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  add_flash_types :success, :info, :warning, :danger

  private

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end

end

app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController
   before_action :set_users 
   before_action :set_group


  def new
    @add = GroupUser.new(id: params[:group_id], id: params[:user_id])
  end

  def create
     @add = GroupUser.create(groupuser_params)
  if @add.save
     redirect_to mypage_path,  success: 'ユーザーを追加しました'
  else
     flash[:alert] = 'このユーザーは追加されています'
     render :new
  end

  end

  private

  def set_users
   @users = User.all
  end

  def set_group
   @group = current_user.groups.all
  end

  def groupuser_params
   params.require(:group_user).permit(:user_id, :group_id)
  end



end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end


  def create
    @group = Group.new(group_params)
  if  @group.save
    @group.users << current_user
    redirect_to group_path(@group), success: 'グループを作成しました'
  else
    flash[:alert] = 'このグループ名は存在します'
    render :new
  end
  end

  def show
    @group = Group.find_by(id: params[:id])
    user = current_user.id
    @post = Post.find_by(user_id: user)
  end



  private

  def group_params
    params.require(:group).permit(:name)
  end

  def post_params
    params.require(:post).permit(:content, :user_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_group

  def new
    @post= Post.new
    @user = current_user.id
  end

  def create
     @user = current_user.id
     @post = Post.new(post_params)
     @post.save
     redirect_to group_path(@group)
  end

  def edit
     user = current_user.id
     @post = Post.find_by(user_id: user)
  end

  def update
     @post = Post.find_by(id: params[:id])
  if @post.update(update_params)
     @post.touch(:created_at)
     flash[:notice] = "体温を更新しました"
     redirect_to group_path(@group)
  end

  end 

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :group_id)
  end

  def update_params
    params.require(:post).permit(:content)
  end

  def set_group
    @group = params[:group_id]
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to mypage_path, success: 'ログインしました'
    else
      render  'top/index'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'ログアウトしました'
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new(flash[:user])
  end

  def create
    @user =  User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to mypage_path, success: '新規登録完了'
    else
      redirect_to :back, flash: {
        user: @user,
        error_messages: @user.errors.full_messages
      }
    end
  end

  def me
     @group = current_user.groups
     @mygroup = Group.find_by(id: params[:id])
  end


  

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

        def header_link_item(name, path)
            class_name = 'nav-item'
            class_name  <<  'active' if current_page?(path)
    
            content_tag :li, class: class_name do
                link_to name, path, class: 'nav-link'
            end
        end
    
        def logged_in?
            session[:user_id].present?
        end
    
         
        def flash_message(message, klass)
           content_tag(:div, class: "alert alert-#{klass}") do
            concat content_tag(:button, 'x', class: 'close', data: {dismiss: 'alert'})
            concat raw(message)
        end
    end
    
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

        def login(user)
            session[:user_id] = user.id
        end
    
        def current_user
            @current_uset ||= User.find_by(id:session[:user_id])
        end
    
        def logged_in?
            !current_user.nil?
        end
    
        def log_out
            session.delete(:user_id)
            @current_user = nil
        end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/group_users/create.html.erb
<h1>GroupUsers#create</h1>
<p>Find me in app/views/group_users/create.html.erb</p>

app/views/group_users/new.html.erb
<div class="newsletter-subscribe">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">ユーザーリスト</h2>
            <p class="text-center">招待するユーザーを選んでください</p>
        </div>

        <%= form_for @add, :url => {action: "create"} do |f| %>

         <%= f.label :group_id, 'グループを選択'%>
         <%= f.collection_select :group_id, @group, :id, :name,  :prompt => "選んでください" %>

         <%= f.label :user_id, '追加するユーザーを選択'%>
         <%= f.collection_select :user_id, @users, :id, :name, :prompt => "選んでください" %>

         <%=  f.submit "addguroup", class: "btn btn-primary" %>
       <% end %>
   </div>
 </div>



 

app/views/groups/add_user.html.erb
<div class="newsletter-subscribe">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">ユーザーリスト</h2>
            <p class="text-center">招待するユーザーを選んでください</p>
        </div>
      <%= form_for @add, url: addgroup_path do |f| %>

         <%= f.label :group_id, 'グループを選択'%>
         <%= f.collection_select :group_id, @group, :id, :name,  :prompt => "選んでください" %>

         <%= f.label :user_id, '追加するユーザーを選択'%>
         <%= f.collection_select :user_id, @users, :id, :name, :prompt => "選んでください" %>

         <%=  f.submit "addguroup", class: "btn btn-primary" %>
       <% end %>
   </div>
 </div>

app/views/groups/new.html.erb
<div class="highlight-clean">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">グループを作成</h2>
            <p class="text-center">・グループ名を記入して下さい</p>
               <%= form_for @group do |f| %>
                <%= f.label :name %> 
                <%= f.text_field :name, class:"form-control"%>
                <%= f.submit "作成", class:"btn btn-primary" %>  
              <% end %>     
    </div>
</div>

app/views/groups/show.html.erb
<div class="highlight-clean">
  <div class="container">
    <div class="intro">
      <h2 class="text-center"><%= @group.name %></h2>
      <div class="text-center">
        <% if current_user.posts.blank? %>
           <%= link_to '体温を投稿しましょう', new_group_post_path(@group), class:"btn btn-success" %>
        <% end %>
      </div >  
    </div>

<div class="main posts-index">
  <div class="container">
    <% @group.users.each do |user| %>
     <% user.posts.each do |post|%>
      <div class="posts-index-item">
        <div class="post-right">
          <div class="post-user-name">
            <%= user.name %>さん   
          </div>
             <div class="text-center"><h3><%= post.content %>度</h3></div>
             <div class="text-right">
              <% if current_user.id == user.id%>
                 <%= link_to '体温投稿', edit_group_post_path(@group,  @post), class:"btn btn-success" %>
              <% end %> 
             <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
             </div>
        </div>
      </div>
    <% end %>
    <% end %>
　　<%= link_to 'ユーザーを追加する', addgroup_path, class:"btn btn-primary btn-block" %>
  </div>
</div>
 </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=devise-width,initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'shared/header' %>
  <%= render partial: 'shared/flash' %>
     <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<div class="newsletter-subscribe">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">体温を投稿する</h2>
        </div>
        <%= form_for @post,  url: group_posts_path do |f| %>
        <div class='form-inline' >      
        <%=  f.number_field  :content, step: "0.1", class: 'form-control' %>
        </div>
        <%= f.submit "体温投稿", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="highlight-clean">
  <div class="container">
      <div class="intro">
            <h2 class="text-center">体温を投稿</h2>

         <%= form_for @post,  :url => {action: "update"} do |f| %>
          <div class='form-group' >      
            <%=  f.number_field  :content, step: "0.1", class: 'form-control' %>
            <%= f.submit "体温投稿", class: "btn btn-primary"%>
          </div>
         <% end %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="newsletter-subscribe">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">体温を投稿する</h2>

        <%= form_for @post,   url: group_posts_path do |f| %>
          <div class='form-inline' >      
            <%=  f.number_field  :content, step: "0.1", class: 'form-control' %>
          </div>
            <%= f.submit "体温投稿", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>
 

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<div class="highlight-clean">
  <div class="container">
      <div class="intro">
            <h2 class="text-center">体温を投稿</h2>

         <%= form_for [@group,  @post],  url: group_post_path do |f| %>
          <div class='form-group' >      
            <%=  f.number_field  :content, step: "0.1", class: 'form-control' %>
            <%= f.submit "体温投稿", class: "btn btn-primary"%>
          </div>
         <% end %>
        </div>
    </div>
</div>

app/views/shared/_flash.html.erb
<div class="alert alert-primary">
<%= flash_message(flash[:success], :success) if flash[:success] %>
<%= flash_message(flash[:error], :danger) if flash[:error] %>
<%= flash_message(flash[:alert], :warning) if flash[:alert] %>
<%= flash_message(flash[:notice], :info) if flash[:notice] %>
</div>

app/views/shared/_footer.html.erb
<div class="footer-clean">
 <footer>
<div class="container">
<div class="row justify-content-center">
<div class="col-sm-4 col-md-3 item">
    <h3>ログインデモユーザー1</h3>
        <ul>
         <li>email 　tesuto1@xxx.jp</li>
         <li>password  111111</li>
        </ul>
</div>

app/views/shared/_header.html.erb
<head>
 <nav class="navbar navbar-light navbar-expand-md" style="background-color: #a8cee2;">
        <div class="container-fluid"><a class="navbar-brand" href="/">みんなの体温</a><button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggler"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse show"
                id="navcol-1">
                <ul class="nav navbar-nav">
                <% if current_user %>

                 <li role="presentation" class="nav-item">
                 <%= link_to 'マイグループ', mypage_path %>
                 
                 
                
                  <%= link_to 'グループ作成', new_group_path%>
                  

                  
                  <%= link_to 'ログアウト', logout_path, :method => :delete, remote: true%>
                 
                  
                  <% else %>

              
                    <%= link_to "新規登録", new_user_path %>
                 

                  
                    <%= link_to "ログイン", login_path %>
                  </li>
                  <% end %>
                </ul>
            </div>
        </div>
    </nav>
</head>

app/views/top/index.html.erb
<div class="highlight-phone">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="intro">
                        <h2>体温を知って貰おう。</h2>
                        <p>Myグループに計測した体温を投稿する簡易デモアプリケーションです。</p>
                        <% if current_user %>
                        <%= link_to 'マイページへ', mypage_path, class:"btn btn-primary"%>
                        <% else %>
                        <%= link_to '新規作成', new_user_path, class:"btn btn-primary" %>
                        <% end %>
                        </div>
                </div>
                        <div class="screen"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="highlight-clean"></div>
    <div class="features-clean">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">みんなの体温とは</h2>
                <p class="text-center">作成したグループ内で体温を共有するデモアプリケーションです</p>
            </div>
            <div class="row features">
                <div class="col-sm-6 col-lg-4 item">
                    <h3 class="name">1.新規登録</h3>
                    <p class="description">新規登録を行いアプリケーションにログインしよう</p>
                </div>
                <div class="col-sm-6 col-lg-4 item">
                    <h3 class="name">2.グループ作成&ユーザー招待</h3>
                    <p class="description">グループを作成し、ユーザーリストから招待したいユーザーを選択して招待しよう</p>
                </div>
                <div class="col-sm-6 col-lg-4 item">
                    <h3 class="name">3.体温を投稿&共有</h3>
                    <p class="description">体温を投稿しグループメンバーに体温を知ってもらいましょう。又、グループメンバーの体温も知りましょう</p>
                </div>
            </div>
        </div>
    </div>


    
    

app/views/users/me.html.erb
      <div class="newsletter-subscribe">
       <div class="container">
         <div class="intro">
             <h2 class="text-center"><%= current_user.name %>さんのマイグループ</h2>
            <p class="text-center">現在参加中のグループ一覧</p>
        </div>
　<% @group.each do |group| %>
　　<div class="list-group">
  　　<div class="list-group-item">
    　　<li><%= link_to group.name, group_path(group) %></li> 
  　 </div>
 　 <% end %>
　</div>

app/views/users/new.html.erb
 <div class="highlight-clean">
  <div class="container">
    <div class="intro">
      <h2 class="text-center">新規登録</h2>
       <%= form_for @user do |f| %>
        <div class='form-group' >
         <%= f.label :name, 'ユーザー名' %>
         <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group" >
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
         </div>
         <div class="form_group" >
           <%= f.label :password, 'パスワード' %>
           <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group" >
          <%= f.label :password_confirmation, 'パスワード（確認）' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
         <%= f.submit "登録する", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>